// src/react/Search.tsx
import React, { useState } from "react";
import { getInfo } from "../server/apiClient";
import { useAsync } from "./useAsync";

export function Search(props: {
  onAdd: (name: string) => void;
}) {
  const [searchValue, setSearchValue] = useState("");

  const infoResult = useAsync(
    "info",
    searchValue.length >= 3 && [searchValue],
    getInfo
  );

  return (
    <div className="search">
      <h2>Search Pokemon</h2>
      <form
        onSubmit={e => {
          e.preventDefault();
          if (infoResult.state !== "done") return;
          props.onAdd(infoResult.data.name);
          setSearchValue("");
        }}
      >
        <input
          value={searchValue}
          onChange={e => setSearchValue(e.target.value)}
        />

        {infoResult.state === "done" && (
          <div className="search-info">
            <img src={infoResult.data!.img} />
            <button>Add to Team</button>
          </div>
        )}
      </form>
    </div>
  );
}

// src/vue/Search.vue
<script>
import { ref, computed } from "@vue/composition-api";
import { useAsync } from "./useAsync";
import { getInfo } from "../server/apiClient";

export default {
  components: {},
  setup(props, context) {
    const search = ref("");

    const { result: infoResult } = useAsync(
      "info",
      computed(() => search.value.length >= 3 && [search.value]),
      getInfo
    );

    function onSubmit(e) {
      e.preventDefault();
      if (infoResult.value.state !== "done") return;
      context.emit("add", infoResult.value.data.name);
      search.value = "";
    }
    return {
      search,
      infoResult,
      onSubmit
    };
  }
};
</script>

<template>
  <div class="search">
    <h2>Search Pokemon</h2>
    <form @submit="onSubmit($event)">
      <input v-model="search" />

      <div class="search-info" v-if="infoResult.state === 'done'">
        <img :src="infoResult.data.img" />
        <button>Add to Team</button>
      </div>
    </form>
  </div>
</template>
