// src/vue/App.vue

<script>
import { ref, watch, watchEffect, computed } from "@vue/composition-api";
import ButtonVue from "./Button.vue";
import InputVue from "./Input.vue";
import { useAsync } from "./useAsync";
import { getTeamNames, removeFromTeam, addToTeam } from "../server/apiClient";
import TeamListVue from "./TeamList.vue";
import DetailsVue from "./Details.vue";

export default {
  components: {
    TeamListVue,
    DetailsVue
  },
  setup(props, context) {
    const { result: membersResult, refetch } = useAsync(
      "team-names",
      ref([]),
      getTeamNames
    );

    const selectedMember = ref(null);

    function onSelect(name) {
      selectedMember.value = name;
    }

    function onRemove(name) {
      removeFromTeam(name).then(refetch);
    }

    function onAdd(name) {
      addToTeam(name).then(refetch);
    }

    return {
      membersResult,
      onAdd,
      onRemove,
      onSelect,
      selectedMember
    };
  }
};
</script>


<template>
  <div>
    <details-vue v-if="selectedMember" :name="selectedMember" @back="selectedMember = null"></details-vue>
    <team-list-vue
      v-if="!selectedMember"
      :names="membersResult.data || []"
      @select="onSelect($event)"
      @remove="onRemove($event)"
      @add="onAdd($event)"
    ></team-list-vue>
  </div>
</template>

// src/react/App.tsx
import React, { useState } from "react";
import {
  addToTeam,
  getTeamNames,
  removeFromTeam
} from "../server/apiClient";
import { Details } from "./Details";
import { TeamList } from "./TeamList";
import { useAsync } from "./useAsync";

export function App() {
  const membersResult = useAsync(
    "team-names",
    [],
    getTeamNames
  );

  const [selectedMember, setSelectedMember] = useState(
    null as string | null
  );

  function onRemove(name: string) {
    removeFromTeam(name).then(membersResult.refetch);
  }

  if (selectedMember) {
    return (
      <Details
        name={selectedMember}
        onBack={() => setSelectedMember(null)}
      ></Details>
    );
  }

  return (
    <>
      <TeamList
        names={membersResult.data ?? []}
        onSelect={name => setSelectedMember(name)}
        onAdd={name =>
          addToTeam(name).then(membersResult.refetch)
        }
        onRemove={onRemove}
      ></TeamList>
    </>
  );
}
