// src/vue/TeamList.vue
<script>
import SearchVue from "./Search.vue";

export default {
  props: {
    names: Array
  },
  components: {
    SearchVue
  },
  setup(props, context) {
    return {};
  }
};
</script>

<template>
  <div>
    <h1>My Pokemon Team</h1>
    <ul class="team-list">
      <li v-for="name in names" :key="name">
        <span class="link" @click="$emit('select', name)">{{name}}</span>
        <span class="link" @click="$emit('remove', name)">remove</span>
      </li>
    </ul>
    <search-vue @add="$emit('add', $event)" />
  </div>
</template>

// src/react/TeamList.tsx
import React from "react";
import { Search } from "./Search";

export function TeamList(props: {
  names: string[];
  onSelect: (name: string) => void;
  onRemove: (name: string) => void;
  onAdd: (name: string) => void;
}) {
  return (
    <div>
      <h1>My Pokemon Team</h1>
      <ul className="team-list">
        {props.names.map(name => (
          <li key={name}>
            <span className="link" onClick={() => props.onSelect(name)}>
              {name}
            </span>
            <span className="link" onClick={() => props.onRemove(name)}>
              remove
            </span>
          </li>
        ))}
      </ul>
      <Search onAdd={props.onAdd} />
    </div>
  );
}
